### ISSUE TITLE
bruh

### ISSUE THREAD

**Issue by Elf514Thefolder** [CelestialCartographers/Ahorn#39] opened 2023-05-06 10:22 UTC
I installed Ahorn, Julia, and Maple, and doesn't launch
[error.log](https://github.com/CelestialCartographers/Ahorn/files/11412090/error.log)

**Comment by Cruor** [comment] 2023-05-07 09:53
Duplicate of https://github.com/CelestialCartographers/Ahorn/issues/36

**Closed by Cruor** 2023-05-07 09:53 UTC
